import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { CheckCircle2, FileText, MessageSquare, Zap } from "lucide-react";

const features = [
  {
    icon: FileText,
    title: "CV Analysis",
    titleEs: "Análisis de CV",
    description:
      "Upload your CV and get a detailed AI-powered breakdown with a score, strengths, and specific improvements.",
    descriptionEs:
      "Sube tu CV y obtén un análisis detallado con puntaje, fortalezas y mejoras específicas.",
  },
  {
    icon: MessageSquare,
    title: "Interview Simulator",
    titleEs: "Simulador de Entrevista",
    description:
      "Practice with role-specific questions generated by AI based on your CV and target position.",
    descriptionEs:
      "Practica con preguntas específicas del puesto generadas por IA con base en tu CV y rol objetivo.",
  },
  {
    icon: Zap,
    title: "Instant Feedback",
    titleEs: "Retroalimentación Instantánea",
    description:
      "Get feedback on your interview answers and tips to improve your responses in real time.",
    descriptionEs:
      "Recibe feedback sobre tus respuestas y consejos para mejorarlas en tiempo real.",
  },
];

const plans = [
  {
    name: "Free",
    price: "$0",
    period: "/month",
    description: "Get started with AI-powered CV analysis",
    features: [
      "1 CV analysis per month",
      "Overall score & summary",
      "Top 3 improvement areas",
      "English & Spanish support",
    ],
    cta: "Start for Free",
    href: "/auth/register",
    highlighted: false,
  },
  {
    name: "Premium",
    price: "$9",
    period: "/month",
    description: "Everything you need to land your next job",
    features: [
      "Unlimited CV analyses",
      "Detailed section-by-section feedback",
      "Interview simulator (unlimited sessions)",
      "AI feedback on your answers",
      "Analysis history",
      "Priority support",
    ],
    cta: "Start Premium",
    href: "/auth/register?plan=premium",
    highlighted: true,
  },
];

export default function LandingPage() {
  return (
    <div className="flex flex-col min-h-screen">
      {/* Navbar */}
      <header className="sticky top-0 z-50 w-full border-b bg-white/80 backdrop-blur">
        <div className="max-w-6xl mx-auto px-4 flex h-16 items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <span className="text-xl font-bold text-primary">CVwise</span>
          </Link>
          <nav className="flex items-center gap-4">
            <Link
              href="#pricing"
              className="text-sm text-muted-foreground hover:text-foreground transition-colors"
            >
              Pricing
            </Link>
            <Link href="/auth/login">
              <Button variant="ghost" size="sm">
                Log in
              </Button>
            </Link>
            <Link href="/auth/register">
              <Button size="sm">Get Started</Button>
            </Link>
          </nav>
        </div>
      </header>

      <main className="flex-1">
        {/* Hero */}
        <section className="py-24 px-4 text-center bg-gradient-to-b from-primary/5 to-white">
          <div className="max-w-4xl mx-auto">
            <Badge variant="secondary" className="mb-4">
              Powered by Claude AI
            </Badge>
            <h1 className="text-5xl font-bold tracking-tight mb-6">
              Land your dream job with{" "}
              <span className="text-primary">AI-powered</span> CV feedback
            </h1>
            <p className="text-xl text-muted-foreground mb-4 max-w-2xl mx-auto">
              Upload your CV, get a detailed analysis and score, then practice
              with a personalized interview simulator. Available in English &
              Spanish.
            </p>
            <p className="text-lg text-muted-foreground mb-8 max-w-2xl mx-auto">
              Sube tu CV, obtén análisis detallado con puntaje, y practica con
              un simulador de entrevistas personalizado.
            </p>
            <div className="flex gap-4 justify-center flex-wrap">
              <Link href="/auth/register">
                <Button size="lg" className="px-8">
                  Analyze my CV — Free
                </Button>
              </Link>
              <Link href="#pricing">
                <Button size="lg" variant="outline" className="px-8">
                  See pricing
                </Button>
              </Link>
            </div>
          </div>
        </section>

        {/* Features */}
        <section className="py-20 px-4 bg-white">
          <div className="max-w-5xl mx-auto">
            <h2 className="text-3xl font-bold text-center mb-12">
              Everything you need to get hired
            </h2>
            <div className="grid md:grid-cols-3 gap-8">
              {features.map((f) => {
                const Icon = f.icon;
                return (
                  <Card key={f.title} className="border-0 shadow-sm">
                    <CardHeader>
                      <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center mb-3">
                        <Icon className="w-5 h-5 text-primary" />
                      </div>
                      <CardTitle className="text-lg">{f.title}</CardTitle>
                      <CardDescription className="text-xs text-muted-foreground/70">
                        {f.titleEs}
                      </CardDescription>
                    </CardHeader>
                    <CardContent>
                      <p className="text-sm text-muted-foreground">
                        {f.description}
                      </p>
                      <p className="text-sm text-muted-foreground/70 mt-1 text-xs italic">
                        {f.descriptionEs}
                      </p>
                    </CardContent>
                  </Card>
                );
              })}
            </div>
          </div>
        </section>

        {/* Pricing */}
        <section id="pricing" className="py-20 px-4 bg-zinc-50">
          <div className="max-w-4xl mx-auto">
            <h2 className="text-3xl font-bold text-center mb-4">
              Simple, transparent pricing
            </h2>
            <p className="text-center text-muted-foreground mb-12">
              Start for free. Upgrade when you need more.
            </p>
            <div className="grid md:grid-cols-2 gap-8">
              {plans.map((plan) => (
                <Card
                  key={plan.name}
                  className={
                    plan.highlighted
                      ? "border-primary shadow-lg relative"
                      : "border shadow-sm"
                  }
                >
                  {plan.highlighted && (
                    <div className="absolute -top-3 left-1/2 -translate-x-1/2">
                      <Badge className="px-3">Most Popular</Badge>
                    </div>
                  )}
                  <CardHeader>
                    <CardTitle>{plan.name}</CardTitle>
                    <CardDescription>{plan.description}</CardDescription>
                    <div className="flex items-baseline gap-1 mt-2">
                      <span className="text-4xl font-bold">{plan.price}</span>
                      <span className="text-muted-foreground">
                        {plan.period}
                      </span>
                    </div>
                  </CardHeader>
                  <CardContent className="space-y-4">
                    <ul className="space-y-2">
                      {plan.features.map((feature) => (
                        <li key={feature} className="flex items-start gap-2">
                          <CheckCircle2 className="w-4 h-4 text-primary mt-0.5 shrink-0" />
                          <span className="text-sm">{feature}</span>
                        </li>
                      ))}
                    </ul>
                    <Link href={plan.href} className="block">
                      <Button
                        className="w-full"
                        variant={plan.highlighted ? "default" : "outline"}
                      >
                        {plan.cta}
                      </Button>
                    </Link>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>
        </section>
      </main>

      {/* Footer */}
      <footer className="border-t py-8 px-4">
        <div className="max-w-6xl mx-auto flex flex-col md:flex-row justify-between items-center gap-4 text-sm text-muted-foreground">
          <span className="font-semibold text-foreground">CVwise</span>
          <span>© {new Date().getFullYear()} CVwise. All rights reserved.</span>
          <div className="flex gap-4">
            <Link href="/privacy" className="hover:text-foreground transition-colors">Privacy</Link>
            <Link href="/terms" className="hover:text-foreground transition-colors">Terms</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
